### ISSUE TITLE
Zig master compiler does not get any updates after first installation

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer-image#110]
After the first installation, the master branch is not updated ever again, because the check at https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_zig_compilers.sh#L11 stops it from re-downloading it. 
That's ok for fixed versions (for example, once 0.3.0 releases, we don't want to download it more than necessary), but for master, it should not be happening.

@tiehuis can you modify the installation script to allow for a fresher master to replace the old one? (We're short on time around here, sorry to bother you with such small things!)

**Comment by tiehuis** [comment]
Will make a PR within the day.
