### ISSUE TITLE
Install newer ICC

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer-image#123]
"2019 Initial Release" is now out

**Comment by mattgodbolt** [comment]
19.1 is now live: we should install this ASAP!

**Comment by mattgodbolt** [comment]
Done and live

**Comment by rscohn2** [comment]
I only see 19.0.1 in the drop-down. How do I use 19.1?

**Comment by partouf** [comment]
> I only see 19.0.1 in the drop-down. How do I use 19.1?

Matt typo'd here, it was 19.0.1 that was installed. We don't have 19.1 currently
