### ISSUE TITLE
Daily Go builds

### ISSUE THREAD

**Issue by vcabbage** [mattgodbolt/compiler-explorer-image#140]
Hi, I'm interested in adding daily Go builds to compiler explorer. It looked like this repo would be the place to start.

The Go project doesn't publish nightly builds. To me, it looks like adding them as part of the `admin-daily-builds.sh` would make sense.

For context, the the high level build process is:

1. Download a pre-built Go toolchain for bootstrapping. (Typically the latest release version.)
2. Clone the source from `go.googlesource.com/go`.
3. Run `GOROOT_BOOTSTRAP=/path/to/bootstrap/toolchain ./make.bash` in `src` directory of the cloned repo.

On my laptop the build takes about 1 minute.

Questions:

* Is this a desirable addition?
* Am I on the right track in terms of adding the builds? I've only done a preliminary review of the scripts here, so I may have missed something.

Thanks!

**Comment by RabsRincon** [comment]
Hi @vcabbage. Thanks for the interest in adding daily Go builds to CE, it IS a super desirable addition. We really appreciate it and we'll try to help as much as possible!

For 1, note that we already install most of the latest Go releases, so you don't need to worry much about how to get one. The rest of your plan soulds solid. Matt probably can give you more help if needed, but you seem to be on the right track.


Let us know if you find any problems :)

**Comment by vcabbage** [comment]
Fantastic! I'll open a PR to add it to the compiler-explorer repo shortly.

**Comment by mattgodbolt** [comment]
Oh! I just pushed a change; let me know if you'd change anything! I CC'd you, is "tip" the right name?

**Comment by vcabbage** [comment]
It's identical to the PR I was about to open :+1: 

I'll go ahead and close this issue. Thanks!

**Comment by mattgodbolt** [comment]
Awesome! Pushing to beta site now: https://godbolt.org/beta (give it 10m or so)
