### ISSUE TITLE
Terraform style improvement

### ISSUE THREAD

**Issue by Cosaquee** [mattgodbolt/compiler-explorer-image#199]
Currently the way Terraform code is written is a bit inconsistent. The style guide on [offical website](https://www.terraform.io/docs/configuration/style.html) suggests to:

```
When multiple arguments with single-line values appear on consecutive lines at the same nesting level, align their equals signs:
```

Example:

This:

```
resource "aws_subnet" "ce-1c" {
  vpc_id = "${aws_vpc.CompilerExplorer.id}"
  cidr_block = "172.30.4.0/24"
  availability_zone = "us-east-1c"
  map_public_ip_on_launch = true

  tags {
    Name = "CompilerExplorer1c"
    Site = "CompilerExplorer"
  }
}
```

would become this:

```
resource "aws_subnet" "ce-1c" {
  vpc_id                  = "${aws_vpc.CompilerExplorer.id}"
  cidr_block              = "172.30.4.0/24"
  availability_zone       = "us-east-1c"
  map_public_ip_on_launch = true

  tags {
    Name = "CompilerExplorer1c"
    Site = "CompilerExplorer"
  }
}
```

I`m happy to submit a pull request if this is something desired.

**Comment by Cosaquee** [comment]
The improved formatting can be found here: https://github.com/Cosaquee/compiler-explorer-image/blob/feature/improve-terraform-code-style/terraform/main.tf. This would be quite a big change in terms of line changes, but there is no new or changed logic.

I would like to improve couple more things, like:

* using `aws_iam_policy_document` data source to make the IAM policies more readable
* avoid hardcoding ACM certs by getting them with data source 
* using local variables

**Comment by mattgodbolt** [comment]
Thanks for the suggestions! Re: formatting, I'm using the built-in formatting of my IDE (IntelliJ) and am a huge fan of auto-format. If I can't configure that to change, we'll be stuck with it as is. (I'm also mildly against such lining-up, but that's a whole other conversation :D, and I prefer consistency over that).

I'd be all for merging a change. But it has to be automatable (either in-IDE, or at a push as a `make` target).

I'd love to see some of the other suggestions: as you can tell I'm a huge terraform noob! I just dumped a bunch more policies in, and will look at `aws_iam_policy_document` right now :). There's also some other hard-coded sources that came in with a recent change. I didn't use `data` for them as some had dire warnings about pulling and storing local secrets in plaintext (!).

Local variables: sounds great!

Thanks for taking the time to help improve CE!

**Comment by mattgodbolt** [comment]
I found I can align at equals in the IDE (yay)

**Comment by Cosaquee** [comment]
Closed by https://github.com/mattgodbolt/compiler-explorer-image/commit/ad087c800e2d8aa141bdc8c36b4ae8b342ee76f2 and https://github.com/mattgodbolt/compiler-explorer-image/commit/24e42d319cc151ad40b7fbae9015d4d932343d16
