### ISSUE TITLE
Clang source code should be fetched from GitHub

### ISSUE THREAD

**Issue by cpplearner** [mattgodbolt/compiler-explorer-image#275]
The LLVM Project has migrated from SVN to GitHub. SVN was retired a few days ago. In response to this, [clang/build/build.sh](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build.sh) should be updated to fetch from https://github.com/llvm/llvm-project/ .

**Comment by mattgodbolt** [comment]
Should be fixed by f35b891d57aebac4b179b866cd5e33dbb8b400ec but will reserve judgment until we've been through a build cycle.

**Comment by mattgodbolt** [comment]
``
Nov/08 14:50 admin-node~/compiler-explorer-image (master|✔) 4.1m $ /opt/compiler-explorer/clang-trunk/bin/clang++ --version
clang version 10.0.0 (https://github.com/llvm/llvm-project.git e25bc5e0247141cb31093a370e22fe3249bdbb05)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
```
I think that's fixed now!
