### ISSUE TITLE
[Rust] thumbv7em-none-eabi doesn't work

### ISSUE THREAD

**Issue by gendx** [mattgodbolt/compiler-explorer-image#297]
Trying the sample Rust code with `rustc 1.40.0` and the compilation flags `-O --target=thumbv7em-none-eabi` triggers the following compiler error:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
Compiler returned: 1
```

Apparently, the `thumbv7em-none-eabi` target was added in https://github.com/mattgodbolt/compiler-explorer-image/pull/94, and is still present in [update_compilers/install_rust_compilers.sh](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_rust_compilers.sh), so I don't really know what's going on under the hood.

**Comment by apmorton** [comment]
This is expected behavior of the rust compiler for this target.

You must specify `#![no_std]` at the top of your source to avoid pulling in `std`, which naturally does not exist for a bare metal target like `thumbv7em-none-eabi`.

See: https://godbolt.org/z/ARK9KG
