### ISSUE TITLE
Fix crosstool-ng builds

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer-image#85]
Since the move to 18.04 the crosstool-ng docker image won't build. Plus we (probably) need to upgrade crosstool-ng too.

**Comment by mattgodbolt** [comment]
@grooverdan fixed this with some awesome patch-fu

**Comment by grooverdan** [comment]
It was backport of a more complicated patch upstream. Probably should push crosstool-ng to do another release.
