### ISSUE TITLE
Blaze library unusable in online version

### ISSUE THREAD

**Issue by FabienPean** [mattgodbolt/compiler-explorer-image#95]
Just including the library seems to exceed the compilation time allowed.

```c++
#include<blaze/Blaze.h>
int square(int num) {
    return num * num;
}
```
Compilation output: 
> Killed - processing time exceeded
> Compiler returned: -1

After ~7500ms, tested with clang 6.0 and gcc 8.1

**Comment by mattgodbolt** [comment]
This is unfortunate and is probably related to #53 - our network file system is not fast enough to handle the read traffic in a timely fashion for big template libraries.

I ran the command on one of the compilation nodes directly under time and it took 22 seconds...

**Comment by mattgodbolt** [comment]
Closing as a duplicate of #53
